version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: actions-on-google
    versions:
    - 2.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
